FROM elixir:1.19-otp-28-alpine

RUN apk add --no-cache build-base git inotify-tools

WORKDIR /app

RUN mix local.hex --force && mix local.rebar --force

EXPOSE 4000

CMD ["sh", "-c", "mix deps.get && mix ecto.create && mix ecto.migrate && mix phx.server"]
